"""Module for Base Model."""

from datetime import datetime
from .database import db


class BaseModel(db.Model):

    """ Base model for all database models.
    attributes:
        id (string, reserved):
             a unique identifier for each instance. Autogenerated.
        deleted (bool, required):
            a flag for soft deletion of model instances.
    """

    __abstract__ = True

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)
    deleted = db.Column(db.Boolean, nullable=True, default=False)
